### PR TITLE
re-doing the student course navigation  #15 #16 #4 #5

### PR DESCRIPTION
**Pull request by MarwaRegal**
@MariamMohamedFawzy @sohaghareb @AnasAshraf @mohamedoufa 
#15 #16 #4 #5 

Documentation for #15 and #16 
I created a a method view_course in the student controller this method is linked to in the show view of the students . in view_course view all courses given in the student's school and their code will be displayed.
I created a method show_course in the student controller , this method is linked to in the view_course view . it shows name and code about a certain subject and enables the student to play the game.
the column school was added to the Subjects table

UML for #15 and #16 
new_uml 1

Documentation #4 and #5 
In the Dashboard of the active admin  the id , school ,email and created add of the School_admins who have not yet been verified will be displayed. there's a link to accept and reject these link redirect to the methods accept and reject in the school_admins_controller. the accept method changes verified to true while the reject method changed the verified to nil.

UML #4 
admin 2

UML #5 
new_uml 3

### CODE REVIEW

**Comment by MariamMohamedFawzy** [comment]
@MarwaRegal There is a syntax error in fixtures of subjects which gives 13 errors in the test of controllers
There must be 2 spaces between the name of the fixture and its attributes

**Comment by MariamMohamedFawzy** [comment]
@MarwaRegal You have also an error regarding the name of your method in line 17 in students_controller_test.rb

**Comment by MarwaRegal** [comment]
@MariamMohamedFawzy I fixed them , can you check now ?

**Comment by MariamMohamedFawzy** [comment]
@MarwaRegal May u modify the name of controller students_controller_controller_test.rb to students_controller_test.rb and add one more space in subjects fixtures

**Comment by MarwaRegal** [comment]
@MariamMohamedFawzy done

**Comment by MariamMohamedFawzy** [comment]
@MarwaRegal Tamam :) all tests have runned successfully

**Pull request merged**
