### PR TITLE
L1 l2 renewal

### PR DESCRIPTION
**Pull request by MMelouk94**
@mohamadbadr @NadineMansour @alisoliman 

Besm allah el rahman el raheem
The first versions of level 1 and 2 were so shitty, they had to be renewed.
So, here's a list of what's different between the new versions and the old ones.
1. a tutorial is given by Mr. Smarty, the player's sidekick and helper.
2. Buttons are more transparent, as it look much better and doesn't make the scene look crowded.
3. the line renderer was replaced by a spot light and a cone-like line renderer.

### CODE REVIEW

**Comment by NadineMansour** [comment]
@MMelouk94 Bro you are awesome !!

**Comment by NadineMansour** [comment]
@MMelouk94 
ShooterScript_1 / ShooterScript_2
remove line 6
line 19 and 24 --> add an extra empty line 
line 58 --> { in a new line 

nextButton_MM.cs / nextButton_MM_2.cs
line 3 —> add an extra line
line 8—> add an extra line 
line 32—> add an extra line

remove any unused method (start / update)

YOU ARE STILL AWESOME !!

**Comment by alisoliman** [comment]
Amazing work.

**Comment by MMelouk94** [comment]
@NadineMansour @alisoliman Rabena yekhaleeko :D

**Comment by MMelouk94** [comment]
#64

**Pull request merged**
