### PR TITLE
view and accept requests #6

### PR DESCRIPTION
**Pull request by AnasAshraf**
@MariamMohamedFawzy  @MarwaRegal @sohaghareb  @mohamedoufa 

external documentation:
-created a view for the requests to be viewed and authorised.
-view_requests is used to view the list of students waiting to be authorised

### CODE REVIEW

**Comment by MMelouk94** [comment]
@AnasAshraf fh typo f file view_requests, line 28

**Comment by MMelouk94** [comment]
<% @current_school_admin_id = 1 %>
@AnasAshraf Leh mabtakhodhash men devise men current school admin?

**Comment by MariamMohamedFawzy** [comment]
@MMelouk94 We will do this in phase 2 as it makes errors in test units so we need to ask zoheiry how to fix these errors in tests

**Comment by MMelouk94** [comment]
@MariamMohamedFawzy tab ma keda el functionality ghalat?

**Comment by MariamMohamedFawzy** [comment]
@MMelouk94 it works, but the error is in test unit. it gives authentication error each time we use the devise methods

**Comment by MariamMohamedFawzy** [comment]
i told nadine that checking on the current users will be done isA in phase2, in phase1 we only do the functionality

**Comment by mohamedoufa** [comment]
@AnasAshraf  
 website/app/views/school_admins/view_requests.html.erb 
	2 extra line --> line 19 and 20 
	line 35 every thing inside <tody> has an extra tab

**Comment by MMelouk94** [comment]
@MariamMohamedFawzy  Asl keda either the tests will fail or the scenario will fail 3shan maby3mlsh el ehna 3ayzeeno. f how can it be merged?

**Comment by MariamMohamedFawzy** [comment]
@MMelouk94 that is what we decided to do with Nadine, I told her in our meeting that checking on the current user will be in phase 2

**Comment by MMelouk94** [comment]
@MariamMohamedFawzy okee.

**Pull request merged**
