### PR TITLE
mariam: modify the db connection in game and add logs #58

### PR DESCRIPTION
**Pull request by MariamMohamedFawzy**
@alisoliman @NadineMansour @mohamadbadr @MMelouk94 
I have only started the routine of saving the record that I have writen in sprint 0 in the end game method and saved logs.

### CODE REVIEW

**Comment by MMelouk94** [comment]
@MariamMohamedFawzy enti 3amalty git add all wala added the files that you just changed/added?

**Comment by MariamMohamedFawzy** [comment]
@MMelouk94 git add --all

**Comment by MMelouk94** [comment]
@MariamMohamedFawzy we shouldn't do that. You modified a couple of files and added 130 files, out of which more than 95% aren't necessary, which increases the files and the size. So, kindly remove that pull request, commit the files you modified and push in another branch.

**Comment by NadineMansour** [comment]
@MariamMohamedFawzy 
player script :-

add an extra empty line before save_record method
every { or } should be in a new line 
and the else is in a new line

**Pull request closed without merging**
